#ifndef __Constants__
#define __Constants__

namespace roboteq {

//////////////////////////// RUNTIME COMMANDS ////////////////////////////
constexpr unsigned char _G           = 0;   // Go to Speed or to Relative Position
constexpr unsigned char _GO          = 0;   // Go to Speed or to Relative Position
constexpr unsigned char _M           = 1;   // 
constexpr unsigned char _MOTCMD      = 1;   // 
constexpr unsigned char _P           = 2;   // Go to Absolute Desired Position
constexpr unsigned char _MOTPOS      = 2;   // Go to Absolute Desired Position
constexpr unsigned char _S           = 3;   // Read Target Velocity in RPM (DS402)
constexpr unsigned char _MOTVEL      = 3;   // Read Target Velocity in RPM (DS402)
constexpr unsigned char _C           = 4;   // Set Encoder Counters
constexpr unsigned char _SENCNTR     = 4;   // Set Encoder Counters
constexpr unsigned char _CB          = 5;   // Set Brushless Counter
constexpr unsigned char _VAR         = 6;   // Set User Variable
constexpr unsigned char _SBLCNTR     = 5;   // Set Brushless Counter
constexpr unsigned char _AC          = 7;   // Set Acceleration
constexpr unsigned char _ACCEL       = 7;   // Set Acceleration
constexpr unsigned char _DC          = 8;   // Set Deceleration
constexpr unsigned char _DECEL       = 8;   // Set Deceleration
constexpr unsigned char _DS          = 9;   // Set All Digital Out Bits
constexpr unsigned char _DOUT        = 9;   // Set All Digital Out Bits
constexpr unsigned char _D1          = 10;  // Set Individual Digital Out Bits
constexpr unsigned char _DSET        = 10;  // Set Individual Digital Out Bits
constexpr unsigned char _D0          = 11;  // Reset Individual Digital Out Bits
constexpr unsigned char _DRES        = 11;  // Reset Individual Digital Out Bits
constexpr unsigned char _R           = 12;  // MicroBasic Run
constexpr unsigned char _H           = 13;  // Load Home Counter
constexpr unsigned char _HOME        = 13;  // Load Home Counter
constexpr unsigned char _EX          = 14;  // Emergency Stop (Until MG)
constexpr unsigned char _ESTOP       = 14;  // Emergency Stop (Until MG)
constexpr unsigned char _MG          = 15;  // Emergency Stop Release (After ESTOP)
constexpr unsigned char _MGO         = 15;  // Emergency Stop Release (After ESTOP)
constexpr unsigned char _MS          = 16;  // Motor Stop in All Modes
constexpr unsigned char _MSTOP       = 16;  // Motor Stop in All Modes
constexpr unsigned char _PR          = 17;  // Go to Relative Desired Position
constexpr unsigned char _MPOSREL     = 17;  // Go to Relative Desired Position
constexpr unsigned char _PX          = 18;  // Next Go to Absolute Desired Position
constexpr unsigned char _NXTPOS      = 18;  // Next Go to Absolute Desired Position
constexpr unsigned char _PRX         = 19;  // Next Go to Relative Desired Position
constexpr unsigned char _NXTPOSR     = 19;  // Next Go to Relative Desired Position
constexpr unsigned char _AX          = 20;  // Next Acceleration
constexpr unsigned char _NXTACC      = 20;  // Next Acceleration
constexpr unsigned char _DX          = 21;  // Next Deceleration
constexpr unsigned char _NXTDEC      = 21;  // Next Deceleration
constexpr unsigned char _B           = 22;  // Set User Boolean Variable
constexpr unsigned char _BOOL        = 22;  // Set User Boolean Variable
constexpr unsigned char _SX          = 23;  // Next Velocity
constexpr unsigned char _NXTVEL      = 23;  // Next Velocity
constexpr unsigned char _CS          = 24;  // CAN Send
constexpr unsigned char _CANSEND     = 24;  // CAN Send
constexpr unsigned char _CG          = 25;  // Set Motor Command via CAN
constexpr unsigned char _CANGO       = 25;  // Set Motor Command via CAN
constexpr unsigned char _RC          = 26;  // Set Pulse Out
constexpr unsigned char _RCOUT       = 26;  // Set Pulse Out
constexpr unsigned char _EES         = 27;  // Save to EEPROM (10,000 cycle limit)
constexpr unsigned char _EESAV       = 27;  // Save to EEPROM (10,000 cycle limit)
constexpr unsigned char _BND         = 28;  // Spectrum Bind
constexpr unsigned char _BIND        = 28;  // Spectrum Bind
constexpr unsigned char _AO          = 29;  // 
constexpr unsigned char _AOUT        = 29;  //
constexpr unsigned char _TX          = 30;  //
constexpr unsigned char _LEFT        = 30;  //
constexpr unsigned char _TV          = 31;  //
constexpr unsigned char _RIGHT       = 31;  //
constexpr unsigned char _CSW         = 32;  //
constexpr unsigned char _CELLSW      = 32;  //
constexpr unsigned char _PSW         = 33;  //
constexpr unsigned char _BMSPSW      = 33;  //
constexpr unsigned char _ASW         = 34;  //
constexpr unsigned char _BMSASW      = 34;  //
constexpr unsigned char _HS          = 49;  //
constexpr unsigned char _ANG         = 65;  //
constexpr unsigned char _ANGLE       = 65;  //
constexpr unsigned char _CW          = 86;  //
constexpr unsigned char _SWS         = 81;  //
constexpr unsigned char _SPL         = 87;  //
constexpr unsigned char _SAC         = 88;  //
constexpr unsigned char _SDC         = 89;  //
constexpr unsigned char _ROM         = 90;  //
constexpr unsigned char _TC          = 91;  //
constexpr unsigned char _POS         = 92;  //
constexpr unsigned char _PSP         = 93;  //
constexpr unsigned char _PAC         = 94;  //
constexpr unsigned char _PDC         = 95;  //
constexpr unsigned char _TSL         = 96;  //
constexpr unsigned char _CSS         = 108; // Set SSI Sensor Counter
constexpr unsigned char _STT         = 112; //
constexpr unsigned char _PXL         = 117; //
constexpr unsigned char _ZER         = 121; //
constexpr unsigned char _MM          = 120; //
constexpr unsigned char _GIQ         = 122; //
constexpr unsigned char _GID         = 123; //
constexpr unsigned char _SCO         = 124; //
constexpr unsigned char _VPM         = 125; //
constexpr unsigned char _MKM         = 131; //
constexpr unsigned char _MKO         = 132; //
constexpr unsigned char _MKP         = 133; //
constexpr unsigned char _MKD         = 134; //
constexpr unsigned char _MKT         = 135; //

//////////////////////////// RUNTIME QUERIES ////////////////////////////
constexpr unsigned char _A           = 0;   // Read Motor Amps
constexpr unsigned char _MOTAMPS     = 0;   // Read Motor Amps
//constexpr unsigned char _M           = 1;   //
//constexpr unsigned char _MOTCMD      = 1;   //
//constexpr unsigned char _P           = 2;   //
constexpr unsigned char _MOTPWR      = 2;   //
//constexpr unsigned char _S           = 3;   //
constexpr unsigned char _ABSPEED     = 3;   //
//constexpr unsigned char _C           = 4;   // Read Encoder Counter Absolute
constexpr unsigned char _ABCNTR      = 4;   // Read Encoder Counter Absolute
//constexpr unsigned char _CB          = 5;   // Read Absolute Brushless Counter
constexpr unsigned char _BLCNTR      = 5;   // Read Absolute Brushless Counter
//constexpr unsigned char _VAR         = 6;   //
constexpr unsigned char _SR          = 7;   //
constexpr unsigned char _RELSPEED    = 7;   //
constexpr unsigned char _CR          = 8;   //
constexpr unsigned char _RELCNTR     = 8;   //
constexpr unsigned char _BCR         = 9;   // Read Brushless Count Relative
constexpr unsigned char _BLRCNTR     = 9;   // Read Brushless Count Relative
constexpr unsigned char _BS          = 10;  // Read BL Motor Speed in RPM
constexpr unsigned char _BLSPEED     = 10;  // Read BL Motor Speed in RPM
constexpr unsigned char _BSR         = 11;  // Read BL Motor Speed as 1/1000 of Max RPM
constexpr unsigned char _BLRSPEED    = 11;  // Read BL Motor Speed as 1/1000 of Max RPM
constexpr unsigned char _BA          = 12;  // Read Battery Amps
constexpr unsigned char _BATAMPS     = 12;  // Read Battery Amps
constexpr unsigned char _V           = 13;  //
constexpr unsigned char _VOLTS       = 13;  //
constexpr unsigned char _D           = 14;  //
constexpr unsigned char _DIGIN       = 14;  //
constexpr unsigned char _DI          = 15;  //
constexpr unsigned char _DIN         = 15;  //
constexpr unsigned char _AI          = 16;  // Read Analog Inputs
constexpr unsigned char _ANAIN       = 16;  // Read Analog Inputs
constexpr unsigned char _PI          = 17;  //
constexpr unsigned char _PLSIN       = 17;  //
constexpr unsigned char _T           = 18;  //
constexpr unsigned char _TEMP        = 18;  //
constexpr unsigned char _F           = 19;  //
constexpr unsigned char _FEEDBK      = 19;  //
constexpr unsigned char _FS          = 20;  //
constexpr unsigned char _STFLAG      = 20;  //
constexpr unsigned char _FF          = 21;  //
constexpr unsigned char _FLTFLAG     = 21;  //
//constexpr unsigned char _B           = 22;  //
//constexpr unsigned char _BOOL        = 22;  //
constexpr unsigned char _DO          = 23;  //
constexpr unsigned char _DIGOUT      = 23;  //
constexpr unsigned char _E           = 24;  //
constexpr unsigned char _LPERR       = 24;  //
constexpr unsigned char _CIS         = 25;  //
constexpr unsigned char _CMDSER      = 25;  //
constexpr unsigned char _CIA         = 26;  //
constexpr unsigned char _CMDANA      = 26;  //
constexpr unsigned char _CIP         = 27;  //
constexpr unsigned char _CMDPLS      = 27;  //
constexpr unsigned char _TM          = 28;  //
constexpr unsigned char _TIME        = 28;  //
constexpr unsigned char _LK          = 29;  //
constexpr unsigned char _LOCKED      = 29;  //
constexpr unsigned char _FID         = 30;  //
constexpr unsigned char _TRN         = 31;  //
constexpr unsigned char _TR          = 32;  //
constexpr unsigned char _TRACK       = 32;  //
constexpr unsigned char _K           = 33;  //
constexpr unsigned char _SPEKTRUM    = 33;  //
constexpr unsigned char _DR          = 34;  //
constexpr unsigned char _DREACHED    = 34;  //
constexpr unsigned char _AIC         = 35;  // Read Analog Input After Conversion
constexpr unsigned char _ANAINC      = 35;  // Read Analog Input After Conversion
constexpr unsigned char _PIC         = 36;  //
constexpr unsigned char _PLSINC      = 36;  //
constexpr unsigned char _MA          = 37;  //
constexpr unsigned char _MEMS        = 37;  //
constexpr unsigned char _CL          = 38;  //
constexpr unsigned char _CALIVE      = 38;  //
constexpr unsigned char _CAN         = 39;  // Read Raw CAN Frame
constexpr unsigned char _CF          = 40;  //
constexpr unsigned char _MGD         = 41;  //
constexpr unsigned char _MGDET       = 41;  //
constexpr unsigned char _MGT         = 42;  //
constexpr unsigned char _MGTRACK     = 42;  //
constexpr unsigned char _MGM         = 43;  //
constexpr unsigned char _MGMRKR      = 43;  //
constexpr unsigned char _MGS         = 44;  //
constexpr unsigned char _MGSTATUS    = 44;  //
constexpr unsigned char _MGY         = 45;  //
constexpr unsigned char _MGYRO       = 45;  //
constexpr unsigned char _MBV         = 46;  //
constexpr unsigned char _MBB         = 47;  //
constexpr unsigned char _FM          = 48;  //
constexpr unsigned char _MOTFLAG     = 48;  //
//constexpr unsigned char _HS          = 49;  //
constexpr unsigned char _HSENSE      = 49;  //
constexpr unsigned char _UID         = 50;  //
constexpr unsigned char _ASI         = 51;  // Read Raw Sin/Cos Sensor
constexpr unsigned char _RAWSENSADC  = 51;  // Read Raw Sin/Cos Sensor
constexpr unsigned char _QO          = 52;  //
constexpr unsigned char _QOUT        = 52;  //
constexpr unsigned char _EO          = 53;  //
constexpr unsigned char _EOUT        = 53;  //
constexpr unsigned char _RMA         = 54;  //
constexpr unsigned char _MACC        = 54;  //
constexpr unsigned char _RMG         = 55;  //
constexpr unsigned char _RGYRO       = 55;  //
constexpr unsigned char _RMM         = 56;  //
constexpr unsigned char _MMAG        = 56;  //
constexpr unsigned char _ML          = 57;  //
constexpr unsigned char _MALL        = 57;  //
constexpr unsigned char _TS          = 58;  //
constexpr unsigned char _LINES       = 58;  //
constexpr unsigned char _MRS         = 59;  //
constexpr unsigned char _MSENS       = 59;  //
constexpr unsigned char _MZ          = 60;  //
constexpr unsigned char _MSZER       = 60;  //
constexpr unsigned char _PK          = 61;  //
constexpr unsigned char _MPEAK       = 61;  //
constexpr unsigned char _RF          = 62;  //
constexpr unsigned char _MREF        = 62;  //
constexpr unsigned char _FIN         = 63;  //
constexpr unsigned char _GY          = 64;  //
constexpr unsigned char _GYRO        = 64;  //
//constexpr unsigned char _ANG       = 65;  // Read Rotor Angle
//constexpr unsigned char _ANGLE     = 65;  // Read Rotor Angle
constexpr unsigned char _HCT         = 66;  //
constexpr unsigned char _HCOUNTER    = 66;  //
constexpr unsigned char _HDT         = 67;  //
constexpr unsigned char _HDATA       = 67;  //
constexpr unsigned char _CUI         = 68;  //
constexpr unsigned char _SCC         = 69;  //
constexpr unsigned char _ICL         = 70;  //
constexpr unsigned char _FC          = 71;  //
constexpr unsigned char _SL          = 72;  //
constexpr unsigned char _PHA         = 73;  //
constexpr unsigned char _CRT         = 74;  //
constexpr unsigned char _CHD         = 75;  //
constexpr unsigned char _BMC         = 76;  // Read BMS State of Charge in AmpHours
constexpr unsigned char _BMF         = 77;  // Read BMS Status Flags
constexpr unsigned char _SOH         = 79;  //
constexpr unsigned char _BMS         = 78;  // Read BMS Switch States
constexpr unsigned char _BSC         = 80;  // Read BMS State of Charge in Percentage
//constexpr unsigned char _SWS       = 81;  //
constexpr unsigned char _MGX         = 82;  //
//constexpr unsigned char _CW        = 86;  //
//constexpr unsigned char _SPL       = 87;  //
//constexpr unsigned char _SAC       = 88;  //
//constexpr unsigned char _SDC       = 89;  //
//constexpr unsigned char _ROM       = 90;  //
//constexpr unsigned char _TC        = 91;  //
//constexpr unsigned char _POS       = 92;  //
//constexpr unsigned char _PSP       = 93;  //
//constexpr unsigned char _PAC       = 94;  //
//constexpr unsigned char _PDC       = 95;  //
//constexpr unsigned char _TSL       = 96;  //
constexpr unsigned char _SW          = 97;  //
constexpr unsigned char _RMP         = 98;  //
constexpr unsigned char _AOM         = 99;  //
constexpr unsigned char _SDM         = 100; //
constexpr unsigned char _VNM         = 101; //
constexpr unsigned char _SS          = 106; //
constexpr unsigned char _SSR         = 107; //
//constexpr unsigned char _CSS       = 108; //
constexpr unsigned char _CSR         = 109; //
constexpr unsigned char _DPA         = 110; //
constexpr unsigned char _SCA         = 111; //
//constexpr unsigned char _STT       = 112; //
constexpr unsigned char _SNS         = 113; //
constexpr unsigned char _PWR         = 114; //
constexpr unsigned char _BEM         = 115; //
constexpr unsigned char _BIN         = 116; //
//constexpr unsigned char _PXL       = 117; //
constexpr unsigned char _IMQ         = 118; //
constexpr unsigned char _SMM         = 119; //
//constexpr unsigned char _MM        = 120; //
constexpr unsigned char _SNA         = 121; //
constexpr unsigned char _TRQ         = 122; //
constexpr unsigned char _FLX         = 123; //
constexpr unsigned char _FLY         = 124; //
constexpr unsigned char _MGW         = 125; //
constexpr unsigned char _MKC         = 126; //
constexpr unsigned char _MKS         = 127; //
constexpr unsigned char _MKE         = 128; //
constexpr unsigned char _MKL         = 129; //
constexpr unsigned char _MKF         = 130; //
//constexpr unsigned char _MKM       = 131; //
//constexpr unsigned char _MKO       = 132; //
//constexpr unsigned char _MKP       = 133; //
//constexpr unsigned char _MKD       = 134; //
//constexpr unsigned char _MKT       = 135; //
constexpr unsigned char _MKV         = 136; //

//////////////////////////// CONFIGURATION ////////////////////////////
constexpr unsigned char _EE           = 0;   //
constexpr unsigned char _BKD          = 1;   //
constexpr unsigned char _OVL          = 2;   //
constexpr unsigned char _UVL          = 3;   //
constexpr unsigned char _THLD         = 4;   //
constexpr unsigned char _MXMD         = 5;   //
constexpr unsigned char _PWMF         = 6;   //
constexpr unsigned char _CPRI         = 7;   //
constexpr unsigned char _RWD          = 8;   //
constexpr unsigned char _ECHOF        = 9;   //
constexpr unsigned char _RSBR         = 10;  //
constexpr unsigned char _ACS          = 11;  //
constexpr unsigned char _AMS          = 12;  //
constexpr unsigned char _CLIN         = 13;  //
constexpr unsigned char _DFC          = 14;  //
constexpr unsigned char _DINA         = 15;  //
constexpr unsigned char _DINL         = 16;  //
constexpr unsigned char _DOA          = 17;  //
constexpr unsigned char _DOL          = 18;  //
constexpr unsigned char _AMOD         = 19;  //
constexpr unsigned char _AMIN         = 20;  //
constexpr unsigned char _AMAX         = 21;  //
constexpr unsigned char _ACTR         = 22;  //
constexpr unsigned char _ADB          = 23;  //
constexpr unsigned char _ALIN         = 24;  //
constexpr unsigned char _AINA         = 25;  //
constexpr unsigned char _AMINA        = 26;  //
constexpr unsigned char _AMAXA        = 27;  //
constexpr unsigned char _APOL         = 28;  //
constexpr unsigned char _PMOD         = 29;  //
constexpr unsigned char _PMIN         = 30;  //
constexpr unsigned char _PMAX         = 31;  //
constexpr unsigned char _PCTR         = 32;  //
constexpr unsigned char _PDB          = 33;  //
constexpr unsigned char _PLIN         = 34;  //
constexpr unsigned char _PINA         = 35;  //
constexpr unsigned char _PMINA        = 36;  //
constexpr unsigned char _PMAXA        = 37;  //
constexpr unsigned char _PPOL         = 38;  //
constexpr unsigned char _MMOD         = 39;  //
constexpr unsigned char _MXPF         = 40;  //
constexpr unsigned char _MXPR         = 41;  //
constexpr unsigned char _ALIM         = 42;  //
constexpr unsigned char _ATRIG        = 43;  //
constexpr unsigned char _ATGA         = 44;  //
constexpr unsigned char _ATGD         = 45;  //
constexpr unsigned char _KP           = 46;  //
constexpr unsigned char _KI           = 47;  //
constexpr unsigned char _KD           = 48;  //
constexpr unsigned char _PIDM         = 49;  //
constexpr unsigned char _ICAP         = 50;  //
constexpr unsigned char _MAC          = 51;  // Set Motor Acceleration in 0.1 RPM/sec.
constexpr unsigned char _MDEC         = 52;  // Set Motor Deceleration in 0.1 RPM/sec.
constexpr unsigned char _MVEL         = 53;  //
constexpr unsigned char _MXRPM        = 54;  // Set Motor Max. Velocity in RPM
constexpr unsigned char _MXTRN        = 55;  //
constexpr unsigned char _CLERD        = 56;  //
constexpr unsigned char _BPOL         = 57;  //
constexpr unsigned char _BLSTD        = 58;  //
constexpr unsigned char _BLFB         = 59;  //
constexpr unsigned char _BHOME        = 60;  //
constexpr unsigned char _BLL          = 61;  //
constexpr unsigned char _BHL          = 62;  //
constexpr unsigned char _BLLA         = 63;  //
constexpr unsigned char _BHLA         = 64;  //
constexpr unsigned char _SPOL         = 65;  //
constexpr unsigned char _OVH          = 66;  //
constexpr unsigned char _ZAIC         = 67;  //
constexpr unsigned char _ZPAO         = 68;  //
constexpr unsigned char _ZPAC         = 69;  //
constexpr unsigned char _ZSMC         = 70;  //
constexpr unsigned char _TELS         = 71;  //
constexpr unsigned char _BRUN         = 72;  //
constexpr unsigned char _EMOD         = 73;  //
constexpr unsigned char _EPPR         = 74;  // Set Encoder Pulses Per Revolution
constexpr unsigned char _ELL          = 75;  //
constexpr unsigned char _EHL          = 76;  //
constexpr unsigned char _ELLA         = 77;  //
constexpr unsigned char _EHLA         = 78;  //
constexpr unsigned char _EHOME        = 79;  //
constexpr unsigned char _SKUSE        = 80;  //
constexpr unsigned char _SKMIN        = 81;  //
constexpr unsigned char _SKMAX        = 82;  //
constexpr unsigned char _SKCTR        = 83;  //
constexpr unsigned char _SKDB         = 84;  //
constexpr unsigned char _SKLIN        = 85;  //
constexpr unsigned char _CEN          = 86;  //
constexpr unsigned char _CNOD         = 87;  //
constexpr unsigned char _CBR          = 88;  //
constexpr unsigned char _CHB          = 89;  //
constexpr unsigned char _CAS          = 90;  //
constexpr unsigned char _CLSN         = 91;  //
constexpr unsigned char _CSRT         = 92;  //
constexpr unsigned char _CTPS         = 93;  //
constexpr unsigned char _SCRO         = 94;  //
constexpr unsigned char _BMOD         = 95;  //
constexpr unsigned char _BADJ         = 96;  // 
constexpr unsigned char _BADV         = 97;  //
constexpr unsigned char _BZPW         = 98;  //
constexpr unsigned char _BFBK         = 99;  //
constexpr unsigned char _BEE          = 100; //
constexpr unsigned char _DIM          = 101; //
constexpr unsigned char _EQS          = 102; //
constexpr unsigned char _WMOD         = 103; //
constexpr unsigned char _IPA          = 104; //
constexpr unsigned char _GWA          = 105; //
constexpr unsigned char _SBM          = 106; //
constexpr unsigned char _IPP          = 107; //
constexpr unsigned char _MACA         = 108; //
constexpr unsigned char _PDNS         = 109; //
constexpr unsigned char _SDNS         = 110; //
constexpr unsigned char _DHCP         = 111; //
constexpr unsigned char _CTT          = 112; //
constexpr unsigned char _ZMT          = 113; //
constexpr unsigned char _ZACC         = 114; //
constexpr unsigned char _ZGYR         = 115; //
constexpr unsigned char _ZMAG         = 116; //
constexpr unsigned char _TPOL         = 117; //
constexpr unsigned char _TWDT         = 118; //
constexpr unsigned char _MDIR         = 119; //
constexpr unsigned char _TXOF         = 120; //
constexpr unsigned char _TINV         = 121; //
constexpr unsigned char _TMS          = 122; //
constexpr unsigned char _TWAD         = 123; //
constexpr unsigned char _ZADJ         = 124; //
constexpr unsigned char _PWMM         = 125; //
constexpr unsigned char _PWMI         = 126; //
constexpr unsigned char _PWMX         = 127; //
constexpr unsigned char _AADJ         = 128; //
constexpr unsigned char _TRF2         = 129; //
constexpr unsigned char _TRF05        = 130; //
constexpr unsigned char _TRF5         = 131; //
constexpr unsigned char _TC2          = 132; //
constexpr unsigned char _TC05         = 133; //
constexpr unsigned char _TC5          = 134; //
constexpr unsigned char _TW2          = 135; //
constexpr unsigned char _TW05         = 136; //
constexpr unsigned char _TW5          = 137; //
constexpr unsigned char _TZER         = 138; //
constexpr unsigned char _GRNG         = 139; //
constexpr unsigned char _GYZR         = 140; //
constexpr unsigned char _KPF          = 141; //
constexpr unsigned char _KIF          = 142; //
constexpr unsigned char _TID          = 143; //
constexpr unsigned char _HDEL         = 144; //
constexpr unsigned char _CTRIM        = 145; //
constexpr unsigned char _LEG          = 146; //
constexpr unsigned char _SSP          = 147; //
constexpr unsigned char _SST          = 148; //
constexpr unsigned char _VPH          = 149; //
constexpr unsigned char _MXS          = 150; //
constexpr unsigned char _MPW          = 151; //
constexpr unsigned char _RFC          = 152; //
constexpr unsigned char _IRR          = 153; //
constexpr unsigned char _ILLR         = 154; //
constexpr unsigned char _ILM          = 155; //
constexpr unsigned char _ILR          = 156; //
constexpr unsigned char _DMOD         = 161; //
constexpr unsigned char _MNOD         = 162; //
constexpr unsigned char _HSM          = 163; //
constexpr unsigned char _SWD          = 164; //
constexpr unsigned char _HPO          = 165; //
constexpr unsigned char _BTNC         = 166; //
constexpr unsigned char _BCHT         = 167; //
constexpr unsigned char _BCLT         = 168; //
constexpr unsigned char _BVHT         = 169; //
constexpr unsigned char _BVLT         = 170; //
constexpr unsigned char _BTNT         = 171; //
constexpr unsigned char _BTHT         = 172; //
constexpr unsigned char _BTLT         = 173; //
constexpr unsigned char _BAHT         = 174; //
constexpr unsigned char _BALT         = 175; //
constexpr unsigned char _NOMC         = 176; //
constexpr unsigned char _CNDU         = 177; //
constexpr unsigned char _CNOV         = 178; //
constexpr unsigned char _CCHT         = 179; //
constexpr unsigned char _BPRC         = 180; //
constexpr unsigned char _BTCD         = 181; //
constexpr unsigned char _ISRG         = 182; //
constexpr unsigned char _CRES         = 183; //
constexpr unsigned char _STYP         = 184; //
constexpr unsigned char _MXRTR        = 185; //
constexpr unsigned char _REDL         = 186; //
constexpr unsigned char _MINOP        = 187; //
constexpr unsigned char _BECC         = 189; //
constexpr unsigned char _SVT          = 190; //
constexpr unsigned char _SSV          = 191; //
constexpr unsigned char _SSF          = 192; //
constexpr unsigned char _HEOF         = 193; //
constexpr unsigned char _HSAT         = 194; //
constexpr unsigned char _RPWB         = 195; //
constexpr unsigned char _RPDS         = 196; //
constexpr unsigned char _RPGR         = 197; //
constexpr unsigned char _RPWD         = 198; //
constexpr unsigned char _FCAL         = 199; //
constexpr unsigned char _ANAM         = 200; //
constexpr unsigned char _EDEC         = 201; //
constexpr unsigned char _MDAL         = 202; //
constexpr unsigned char _MNRPM        = 203; //
constexpr unsigned char _FSA          = 204; //
constexpr unsigned char _SCPR         = 206; //
constexpr unsigned char _SWMAN        = 205; //
constexpr unsigned char _STO          = 207; //
constexpr unsigned char _RS485        = 208; //
constexpr unsigned char _OTL          = 209; //
constexpr unsigned char _ZSRM         = 210; //
constexpr unsigned char _ZCAL         = 211; //
constexpr unsigned char _ZANG         = 212; //
constexpr unsigned char _MLX          = 213; //
constexpr unsigned char _SMOD         = 214; //
constexpr unsigned char _SLL          = 215; //
constexpr unsigned char _SHL          = 216; //
constexpr unsigned char _SLLA         = 217; //
constexpr unsigned char _SHLA         = 218; //
constexpr unsigned char _SHOME        = 219; //
constexpr unsigned char _VIND         = 220; //
constexpr unsigned char _CCFG         = 221; //
constexpr unsigned char _SMPT         = 222; //
constexpr unsigned char _TNM          = 223; //
constexpr unsigned char _SBEE         = 224; //
constexpr unsigned char _PSA          = 225; //
constexpr unsigned char _MSP          = 226; //

} // namespace roboteq
#endif
